<a href="https://colab.research.google.com/github/TzurV/TestMe/blob/master/Learn20200514.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#from functools import reduce

a = []
for b in range(1,5):
  print(b)
  a.insert(0,b)
  a.append(b)

print(a)




1
2
3
4
[4, 3, 2, 1, 1, 2, 3, 4]


https://www.w3schools.com/python/python_lambda.asp

Syntax
lambda arguments : expression

We use lambda functions when we require a nameless function for a short period of time.


In [0]:
x = lambda a : a + 10
print(x(5))
x = lambda a, b : a * b
print(x(5, 6))

# Program to filter out only the even items from a list
my_list = [1, 5, 4, 6, 8, 11, 3, 12]

new_list = list(filter(lambda x: (x%2 == 0) , my_list))

print(new_list)


# Program to double each item in a list using map()

my_list = [1, 5, 4, 6, 8, 11, 3, 12]

new_list = list(map(lambda x: x * 2 , my_list))

print(new_list)

15
30
[4, 6, 8, 12]
[2, 10, 8, 12, 16, 22, 6, 24]


Tuple Values
Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.

In [0]:
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

#Create a tuple with different data types
tuplex = ("tuple", False, 3.2, 1)
print(tuplex)

MyList = [12, 33, 'aaa', False]
print(MyList)

tuplex1 = tuplex
MyList1 = MyList

MyList
MyList1
tuplex
tuplex1

print(type(tuplex))
print(dir(tuplex))
print(id(tuplex), id(tuplex1))







('apple', 'kiwi', 'cherry')
('tuple', False, 3.2, 1)
[12, 33, 'aaa', False]
<class 'tuple'>
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
140289730197768 140289730197768


Set
A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets.

Access Items
You cannot access items in a set by referring to an index, since sets are unordered the items has no index.

But you can loop through the set items using a for loop, or ask if a specified value is present in a set, by using the in keyword.

You can also use the pop(), method to remove an item, but this method will remove the last item. Remember that sets are unordered, so you will not know what item that gets removed.

The return value of the pop() method is the removed item.


In [0]:
thisset = {"apple", "banana", "cherry"}
print(thisset)


for x in thisset:
  print(x)

thisset.add("orange")
print(thisset)

thisset.update(["orange", "mango", "grapes"])

print(thisset)

x = thisset.pop()

print(x)

print(thisset)


{'apple', 'cherry', 'banana'}
apple
cherry
banana
{'orange', 'apple', 'cherry', 'banana'}
{'orange', 'mango', 'apple', 'cherry', 'grapes', 'banana'}
orange
{'mango', 'apple', 'cherry', 'grapes', 'banana'}


Dictionary
A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.

In [0]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
print(thisdict["model"])

x = thisdict.get("model")

#Change Values
thisdict["year"] = 2018

#Loop Through a Dictionary
for x in thisdict:
  print(x)

#Print all values in the dictionary
for x in thisdict:
  print(thisdict[x])
for x in thisdict.values():
  print(x)

#Loop through both keys and values
for x, y in thisdict.items():
  print(x, ":", y)


#Copy a Dictionary
#You cannot copy a dictionary simply by typing dict2 = dict1, because: dict2 will only be a reference to dict1, 
# and changes made in dict1 will automatically also be made in dict2.

mydict = thisdict.copy()
print(mydict)

print(id(mydict), id(thisdict))

# Make a copy of a dictionary with the dict() function:
mydict = dict(thisdict)

#dict() Constructor
thisdict = dict(brand="Ford", model="Mustang", year=1964)
# note that keywords are not string literals
# note the use of equals rather than colon for the assignment
print(thisdict)


{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang
brand
model
year
Ford
Mustang
2018
Ford
Mustang
2018
brand : Ford
model : Mustang
year : 2018
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}
140289729837240 140289729836664
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [0]:
# Why Python Is Great:
# Function argument unpacking

def myfunc(x, y, z):
    print(x, y, z)

tuple_vec = (1, 0, 1)
dict_vec = {'x': 1, 'y': 0, 'z': 1}

myfunc(*tuple_vec)

myfunc(**dict_vec)

dict_vec1 = {'x1': 1, 'y': 0, 'z': 1}

# this will fail
#myfunc(**dict_vec1)


def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")

# The phrase Keyword Arguments are often shortened to kwargs in Python documentations.


# function definitions cannot be empty, put in the pass statement to avoid getting an error.
def myfunction():
  pass

1 0 1
1 0 1
The youngest child is Linus


In [0]:
# classes

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)    

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

p1.myfunc()

# The self Parameter
#The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.
#It does not have to be named self , you can call it whatever you like, but it has to be the first parameter of any function in the class:


class Person1:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age

  def myfunc(abc):
    print("Hello my name is " + abc.name)

p1 = Person1("John", 36)
p1.myfunc()


John
36
Hello my name is John
Hello my name is John


In [0]:
mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))


mytuple = {"apple", "banana", "cherry"}
myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))

b
a
n
a
n
a
banana
apple
cherry


In [0]:
def myfunc():
  global x
  x = 300
  print(x)

myfunc()

print(x)

300
300


https://www.w3schools.com/python/python_modules.asp

# What is a Module?
Consider a module to be the same as a code library.

A file containing a set of functions you want to include in your application.

# python dates
https://www.w3schools.com/python/python_datetime.asp


In [0]:
# Python Dates

import datetime

x = datetime.datetime.now()
print(x)

print(x.year)
print(x.strftime("%A - %H - %b"))

2020-05-18 16:30:05.706145
2020
Monday - 16 - May


In [0]:
# RegEx in Python
import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)
print(x)

x = re.findall("ai", txt)
print(x)

x = re.search("\s", txt)
print("The first white-space character is located in position:", x.start())

x = re.finditer("ai", txt)
print(id(x), " ", type(x))
for b in x:
  print(b)

#  "\s" is white space
x = re.split("\s", txt)
print(x)

import this

<_sre.SRE_Match object; span=(0, 17), match='The rain in Spain'>
['ai', 'ai']
The first white-space character is located in position: 3
140136600758368   <class 'callable_iterator'>
<_sre.SRE_Match object; span=(5, 7), match='ai'>
<_sre.SRE_Match object; span=(14, 16), match='ai'>
['The', 'rain', 'in', 'Spain']
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementati

In [15]:
# Python NumPy

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

# Create a 0-D array with value 42 - one element
arr0 = np.array(42)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr0.ndim, " ", arr2.ndim)

#==============
#Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

npr = np.random.rand(3,2,2)
print(npr.ndim)
print(npr)

print(npr[2,1,1])
print("--")

#Slicing arrays
print(npr[1:2,1,:])





[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
0   2
[[[[[1 2 3 4]]]]]
number of dimensions : 5
3
[[[0.14815855 0.3156179 ]
  [0.17906167 0.61144368]]

 [[0.20377381 0.23639003]
  [0.46232359 0.12403448]]

 [[0.34947437 0.35936366]
  [0.76221055 0.6490745 ]]]
0.6490745001497558
--
[[0.46232359 0.12403448]]
